name: Thử nghiệm đọc file README 

on: 
  push: 
    branches: ["main"]  #Chạy khi có code mới đẩy lên nhánh main 

jobs: 
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Buoc 1 - Xin chao
        run: echo "Hello HUTECH"

      - name: Buoc 2 - Tai code
        uses: actions/checkout@v6.0.2

      - name: Buoc 3 - Doc file 
        run: cat README.md

    


